UserConfig:
  Id: 0 #default 0 You can check the list of devices 'adb devices' in terminal or cmd, counting the first device as Id 0.
  IPaddress : "127.0.0.1" #default 127.0.0.1 ip loop back
  Port: "2000" # default 2000 port
  Bitrate: 100000000 # default 100000000
  Resolution: 1280
  Emu: 0 # ID emulator
  GameId: 0 # ID game
  GPU: false # Use gpu processing for detection mode 

#### Emulator list ####
# 0: BlueStacks,
# 1: LDPlayer

#### Game list ####
# 0 : ragnarok labyrinth nft